sudo: required
services:
  - docker

before_install:
  - docker build -t ranugoldan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ranugoldan/docker-react npm run test -- --coverage
